version: 0.2

phases:
  install:
    commands:
      - echo "Building Lambda layer for mapp_hootsuit_data_fetch function..."
      - echo "Docker version:"
      - docker --version
      
  build:
    commands:
      - echo "Building inside Lambda Python 3.11 runtime container..."
      - |
        docker run --rm \
          -v "$PWD":/var/task \
          public.ecr.aws/lambda/python:3.11 \
          /bin/sh -c "
            cd /var/task && \
            echo 'Installing packages from requirements.txt...' && \
            pip install -r requirements.txt -t python/ --no-cache-dir && \
            echo 'Creating Lambda layer zip...' && \
            zip -r python.zip python/
          "
      - echo "Layer package created successfully"
      - ls -lh python.zip
      
  post_build:
    commands:
      - echo "Uploading layer to S3..."
      - aws s3 cp python.zip s3://fluency-ccs-co-gsc-planning-and-evaluation-tool-uk/hootsuit_library/python.zip
      - echo "Upload complete!"
      - echo "Layer is ready to be attached to mapp_hootsuit_data_fetch Lambda function"
      
artifacts:
  files:
    - python.zip
