version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies for Lambda Python 3.11..."
      - python --version
      - pip --version
      
      # Force pip to use compatible manylinux versions for Lambda
      - echo "Installing with Lambda-compatible binary wheels..."
      - pip install --platform manylinux2014_x86_64 --only-binary=:all: -r requirements.txt -t my-library/python
      
  build:
    commands:
      - echo "Zipping the python folder..."
      - cd my-library
      - zip -r ../python.zip python
      - cd ..
      - echo "Package size:"
      - ls -lh python.zip
      
  post_build:
    commands:
      - echo "Uploading the library zip to S3..."
      - aws s3 cp python.zip s3://wikitablescrapexample/libraries/python.zip
      - echo "Upload complete!"
      
artifacts:
  files:
    - python.zip
