version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies into library..."
      - pip install -r requirements.txt -t my-library/python/lib/python3.11/site-packages

  build:
    commands:
      - echo "Zipping the library..."
      - cd my-library
      - zip -r ../my_library.zip .

  post_build:
    commands:
      - echo "Uploading the library to S3..."
      - aws s3 cp ../my_library.zip s3://wikitablescrapexample/libraries/my_library.zip

artifacts:
  files:
    - my_library.zip

