version: 0.2

phases:
  install:
    commands:
      - echo "Pulling Lambda Python 3.11 image..."
      - docker pull public.ecr.aws/lambda/python:3.11
      
  build:
    commands:
      - echo "Creating directory structure..."
      - mkdir -p python
      
      - echo "Installing packages in Lambda environment..."
      - docker run --rm -v "$PWD":/var/task public.ecr.aws/lambda/python:3.11 pip install --target /var/task/python paramiko
      
      - echo "Creating zip file..."
      - zip -r python.zip python/
      
      - echo "Verifying zip was created..."
      - ls -lh python.zip
      
  post_build:
    commands:
      - echo "Checking if python.zip exists..."
      - |
        if [ -f python.zip ]; then
          echo "File exists, uploading to S3..."
          aws s3 cp python.zip s3://fluency-ccs-co-gsc-planning-and-evaluation-tool-uk/hootsuit_library/python.zip
          echo "Upload complete!"
        else
          echo "Error: python.zip not found"
          exit 1
        fi
      
artifacts:
  files:
    - python.zip
